kind: pipeline
type: exec
name: default

platform:
  os: windows
  # arch: amd64
  # version: "1809"

steps:
  - name: build
    # image: mcr.microsoft.com/dotnet/framework/sdk:4.8
    commands:
      - pwsh
      #
      # - curl.exe -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
      - nuget.exe restore WebApplication1.sln
      #
      - msbuild "WebApplication1\WebApplication1.csproj" /p:Configuration=Release -r:False /p:DeployOnBuild=True /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:publishUrl=../output
      - ls ./output
      - pwd

  - name: docker-build
    # image: docker:dind
    environment:
      VERSION: "1.0.${DRONE_BUILD_NUMBER}"
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      # - docker info
      - pwsh
      - pwd
      - ls ./output
      - cp -r ./output ./devops/wwwroot
      - cd ./devops
      - ./build.ps1

  # - name: github-release
  #   image: plugins/github-release
  #   settings:
  #     api_key: xxxxxxxx
  #     files: dist/*
  #

  #
---
kind: pipeline
type: docker
name: deployment-uat

steps:
  - name: deploy
    image: quay.io/honestbee/drone-kubernetes
    settings:
      kubernetes_server:
        from_secret: xclubsys_kubernetes_server
      kubernetes_token:
        from_secret: xclubsys_kubernetes_token
      namespace: default
      deployment: test
      repo: pkgs.azaas.xyz/test-images/test
      container: web
      tag: "1.0.${DRONE_BUILD_NUMBER}"
trigger:
  event:
    - promote
  target:
    - uat
#
# depends_on:
#   - source
