kind: pipeline
type: docker
name: build

# windows required
platform:
  os: windows
  arch: amd64
  # version: "1903"

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/framework/sdk:4.8
    commands:
      #
      - curl.exe -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
      - nuget restore WebApplication1.sln
      #
      - msbuild "WebApplication1\WebApplication1.csproj" /p:Configuration=Release -r:False /p:DeployOnBuild=True /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:publishUrl=../output
      - dir ./output
# MSBuild %PROJECT%  /p:DeployOnBuild=True /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:publishUrl=%PUBLISH_DIRECTORY%
